In [143]:
import numpy as np

# Creating Levenshtein Matrix:
def Levenshtein_Matrix(str1, str2):
  
  # Finding length of strings
  col = len(str1)
  row = len(str2)
  
  # Creating a n x m matrix
  grid = np.zeros((row + 1, col + 1))
  
  # Initializing matrix with string's positions
  for x in range(col+1):
    grid[0][x] = x

  for y in range(row+1):
    grid[y][0] = y

  # Comparing Characters and Filling the Grid/Matrix
  for i in range(1, row + 1):
    for j in range(1, col + 1):
      if (str1[j-1] != str2[i-1]): # If character of strings are not equal
      
        lev1 = grid[i-1][j] + 1  # lev(a,b) = (i - 1, j) + 1
        lev2 = grid[i][j-1] + 1  # lev(a,b) = (i, j - 1) + 1
        lev3 = grid[i-1][j-1] + 1  # lev(a,b) = (i - 1, j - 1) + 1
        grid[i][j] = min(lev1, lev2, lev3) # minimum of all costs

      else: # If character of strings are equal
        grid[i][j] = grid[i-1][j-1] # max(i, j)

  print("\n", grid)
  print("\n Levenshtein Distance is: ", int(grid[row][col]))


# To keep track of operations performed to transform the string
def Count_Operations(str1, str2):

  global insert
  global delete
  global substitute
  count = 0
  
   # Insertion
  if (len(str1) < len(str2)):
   diff = len(str2) - len(str1)
   insert += diff

  # Deletion
  elif (len(str1) > len(str2)):
   diff = len(str1) - len(str2)
   delete += diff
       
  # Substitution
  for i in range(len(str1)):
    for j in range(len(str2)):
     
     # if character matches, don't substitute
     if (str1[i] == str2[j]):
      count +=1
    
    # If no character matches, substitute it
    if(count == 0):
      substitute += 1
    count = 0


### Main Program ###

insert, delete, substitute = 0, 0, 0

str1 = input("Enter String: ")
str2 = input("Transform Into: ")

# Displaying Levenshtein Matrix
Levenshtein_Matrix(str1, str2)

# Counting Character Edits
Count_Operations(str1, str2)

print("\nTotal Number of Substitutions Are: ", substitute)
print("Total Number of Insertions Are: ", insert)
print("Total Number of Deletions Are: ", delete)

Enter String: man
Transform Into: women

 [[0. 1. 2. 3.]
 [1. 1. 2. 3.]
 [2. 2. 2. 3.]
 [3. 2. 3. 3.]
 [4. 3. 3. 4.]
 [5. 4. 4. 3.]]

 Levenshtein Distance is:  3

Total Number of Substitutions Are:  1
Total Number of Insertions Are:  2
Total Number of Deletions Are:  0


In [5]:
import numpy as np

# Creating Levenshtein Matrix:
def Levenshtein_Matrix(str1, str2, f3):
  
  # Finding number of words in each file  
  # Splitting words based on space " "
  for i in str1:
   word = i.split()

  for j in str2:
   word2 = j.split()

  col = len(word)
  row = len(word2)

  # Creating a n x m matrix
  grid = np.zeros((row + 1, col + 1))
  
  # Initializing matrix with string's positions
  for x in range(col+1):
    grid[0][x] = x

  for y in range(row+1):
    grid[y][0] = y

  # Comparing Characters and Filling the Grid/Matrix
  
  m1 = [x.split() for x in str1]
  m2 = [y.split() for y in str2]
  
  for i in range(1, row + 1):
    for j in range(1, col + 1):
      if (m1[0][j-1] != m2[0][i-1]): # If words are not same
      
        lev1 = grid[i-1][j] + 1  # lev(a,b) = (i - 1, j) + 1
        lev2 = grid[i][j-1] + 1  # lev(a,b) = (i, j - 1) + 1
        lev3 = grid[i-1][j-1] + 1  # lev(a,b) = (i - 1, j - 1) + 1
        grid[i][j] = min(lev1, lev2, lev3) # minimum of all costs

      else: # If words are same
        grid[i][j] = grid[i-1][j-1] # max(i, j)

  print("Levenshtein Matrix:\n\n", grid)
  f3.write("Levenshtein Distance is: "+ str(int(grid[row][col])))


# To keep track of operations performed to transform the string
def Count_Operations(str1, str2, f3):

  global insert
  global delete
  global substitute
  count = 0

  # Finding number of words in each file  
  for i in str1:
   word = i.split()

  for j in str2:
   word2 = j.split()

  m1 = [x.split() for x in str1]
  m2 = [y.split() for y in str2]
  
   # Insertion
  if (len(word) < len(word2)):
   diff = len(word2) - len(word)
   insert += diff

  # Deletion
  elif (len(word) > len(word2)):
   diff = len(word) - len(word2)
   delete += diff
       
  # Substitution
  for i in range(len(word2)):
    for j in range(len(word2)):

      # if words match, don't substitute
      if (m1[0][i] == m2[0][j]):
       count += 1

    # Else, substitute
    if (count == 0):
      substitute += 1
    count = 0

      
  f3.write("\nTotal Number of Substitutions Are: "+ str(substitute))
  f3.write("\nTotal Number of Insertions Are: " + str(insert))
  f3.write("\nTotal Number of Deletions Are: "+ str(delete))


def Display_Files(f1, f2, f3):
  
  print("\n*****", f1.name, "*****\n")
  print(str1[0])
  print("\n***********************")

  print("\n\n*****", f2.name, "*****\n")
  print(str2[0])
  print("\n************************")

  print("\n\n*****", f3.name, "*****\n")
  print(f3.read())
  print("\n*********************")

### Main Program ###

insert, delete, substitute = 0, 0, 0

# Creating Files
f1 = open("reference.txt", 'w')
f2 = open("hypothesis.txt", 'w')
f3 = open("result.txt", 'w')

# Entering Text in Files
f1.write("this is some text and we would like to see if it has been identified correctly by speech recognition system")
f2.write("this is a text and we would like to check what has been identified by the speech recognition")

# Closing files
f1.close()
f2.close()

# Calculating Levenshtein Distance
f1 = open("reference.txt", 'r')
f2 = open("hypothesis.txt", 'r')

str1 = f1.readlines()
str2 = f2.readlines()
Levenshtein_Matrix(str1, str2, f3)

# Counting Character Edits
Count_Operations(str1, str2, f3)

# Displaying Result
f3 = open("result.txt", 'r')
Display_Files(f1, f2, f3)


Levenshtein Matrix:

 [[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.
  17. 18. 19.]
 [ 2.  1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.
  16. 17. 18.]
 [ 3.  2.  1.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.
  16. 17. 18.]
 [ 4.  3.  2.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.
  15. 16. 17.]
 [ 5.  4.  3.  3.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.
  14. 15. 16.]
 [ 6.  5.  4.  4.  3.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.
  13. 14. 15.]
 [ 7.  6.  5.  5.  4.  3.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.
  12. 13. 14.]
 [ 8.  7.  6.  6.  5.  4.  3.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.
  11. 12. 13.]
 [ 9.  8.  7.  7.  6.  5.  4.  3.  2.  1.  2.  3.  4.  5.  6.  7.  8.  9.
  10. 11. 12.]
 [10.  9.  8.  8.  7.  6.  5.  4.  3.  2.  2.  3.  4.  5.  6.  7.  8.  9.
  10. 11. 12.]

In [4]:
import numpy as np

# Creating Levenshtein Matrix:
def Levenshtein_Matrix(str1, str2, f3):
  
  # Finding number of words in each file  
  for i in str1:
   word = i.split()

  for j in str2:
   word2 = j.split()

  col = len(word)
  row = len(word2)

  # Creating a n x m matrix
  grid = np.zeros((row + 1, col + 1))
  
  # Initializing matrix with string's positions
  for x in range(col+1):
    grid[0][x] = x

  for y in range(row+1):
    grid[y][0] = y

  # Comparing Characters and Filling the Grid/Matrix
  
  m1 = [x.split() for x in str1]
  m2 = [y.split() for y in str2]
  
  for i in range(1, row + 1):
    for j in range(1, col + 1):
      if (m1[0][j-1] != m2[0][i-1]): # If words are not same
      
        lev1 = grid[i-1][j] + 1  # lev(a,b) = (i - 1, j) + 1
        lev2 = grid[i][j-1] + 1  # lev(a,b) = (i, j - 1) + 1
        lev3 = grid[i-1][j-1] + 1  # lev(a,b) = (i - 1, j - 1) + 1
        grid[i][j] = min(lev1, lev2, lev3) # minimum of all costs

      else: # If words are same
        grid[i][j] = grid[i-1][j-1] # max(i, j)

  print("\n", grid)
  f3.write("Levenshtein Distance is: "+ str(int(grid[row][col])))


# To keep track of operations performed to transform the string
def Count_Operations(str1, str2, f3):

  global insert
  global delete
  global substitute
  count = 0

  # Words to be ignored
  ignore = ["the", "of", "and", "a", "be", "this", "there", "an", "been", "some" ]

  # Finding number of words in each file  
  for i in str1:
   word = i.split()

  for j in str2:
   word2 = j.split()

  m1 = [x.split() for x in str1]
  m2 = [y.split() for y in str2]
  
   # Insertion
  if (len(word) < len(word2)):
   diff = len(word2) - len(word)
   insert += diff

  # Deletion
  elif (len(word) > len(word2)):
   diff = len(word) - len(word2)
   delete += diff
       
  # Substitution
  for i in range(len(word2)):
    for j in range(len(word2)):

      # if word matches, don't substitute
      if (m1[0][i] == m2[0][j]):
       count += 1

    if (count == 0):
      substitute += 1
    count = 0
  
  # Ignoring Substitution
  for k in range(len(word2)):

    if(m1[0][k] != m2[0][k]):
      if m1[0][k] in ignore:
        if m2[0][k] in ignore:
          substitute -= 1

  # Sum of single edit operations = levenshtein distance
  distance = substitute + insert + delete

  f3.write("\nLevenshtein distance is " + str(distance))
  f3.write("\nTotal Number of Substitutions Are: "+ str(substitute))
  f3.write("\nTotal Number of Insertions Are: " + str(insert))
  f3.write("\nTotal Number of Deletions Are: "+ str(delete))


def Display_Files(f1, f2, f3):
  
  print("\n*****", f1.name, "*****\n")
  print(str1[0])
  print("\n***********************")

  print("\n\n*****", f2.name, "*****\n")
  print(str2[0])
  print("\n************************")

  print("\n\n*****", f3.name, "*****\n")
  print(f3.read())
  print("\n*********************")

### Main Program ###

insert, delete, substitute = 0, 0, 0

# Creating Files
f1 = open("reference.txt", 'w')
f2 = open("hypothesis.txt", 'w')
f3 = open("result.txt", 'w')

# Entering Text in Files
f1.write("this is some text and we would like to see if it has been identified correctly by speech recognition system")
f2.write("this is a text and we would like to check what has been identified by the speech recognition")

# Closing files
f1.close()
f2.close()

# Calculating Levenshtein Distance
f1 = open("reference.txt", 'r')
f2 = open("hypothesis.txt", 'r')

str1 = f1.readlines()
str2 = f2.readlines()
#Levenshtein_Matrix(str1, str2, f3)

# Counting Character Edits
Count_Operations(str1, str2, f3)

# Displaying Result
f3 = open("result.txt", 'r')
Display_Files(f1, f2, f3)



***** reference.txt *****

this is some text and we would like to see if it has been identified correctly by speech recognition system

***********************


***** hypothesis.txt *****

this is a text and we would like to check what has been identified by the speech recognition

************************


***** result.txt *****


Levenshtein distance is 5
Total Number of Substitutions Are: 3
Total Number of Insertions Are: 0
Total Number of Deletions Are: 2

*********************


of
